<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>appcontainerexe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<PreferNativeArm64>true</PreferNativeArm64>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<MileXamlNoSunValleyXamlStyle>true</MileXamlNoSunValleyXamlStyle>
	</PropertyGroup>

	<PropertyGroup>
		<AppxPackage>true</AppxPackage>
		<EnableMsixTooling>true</EnableMsixTooling>
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

	<ItemGroup>
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.26100.4654" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" IncludeAssets="build" PrivateAssets="all" IsImplicitlyDefined="true" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.20250806.1" IncludeAssets="build" PrivateAssets="all" IsImplicitlyDefined="true" />
		<PackageReference Include="Mile.Xaml" Version="2.5.1250" IncludeAssets="build" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\*" />
	</ItemGroup>
</Project>
